name: dp2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.2.*
  - tensorflow=2.4.*
  - ipykernel
  - matplotlib=3.4.*
  - pycaret=2.3.*
  - xgboost=1.4.*
  - catboost=0.26.*
  - seaborn=0.11.*
  - pip=21.1.*
  - pip:
    - kaggle
    - scikit-learn~=0.23.2
    - "--editable=git+https://github.com/def-gthill/bobs.git#egg=bobs"
