name: dp1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - tensorflow
  - ipykernel
  - matplotlib
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - kaggle
    - "--editable=git+https://github.com/def-gthill/bobs.git#egg=bobs"
