name: dp1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.2.*
  - tensorflow=2.4.*
  - ipykernel
  - matplotlib=3.4.*
  - scikit-learn=0.24.*
  - seaborn=0.11.*
  - pip=21.1.*
  - pip:
    - kaggle
    - "--editable=git+https://github.com/def-gthill/bobs.git#egg=bobs"
